feat: added enabled field in metadata.
optimizely/java-sdk pull request #409
Opened 2020-11-10 15:56 UTC by mnoman09

## Summary
- While sending impression events, metadata should have enabled field as well.

## Test plan
- updated unit tests
- FSC should pass

2020-11-10 17:08 UTC, jaeopt requested changes

2020-11-12 17:44 UTC, jaeopt approved these changes
LGTM

2020-11-12 22:49 UTC, pawels-optimizely commented on core-api/src/main/java/com/optimizely/ab/event/internal/payload/DecisionMetadata.java
> +        this.enabled = enabled;
why did we add it if it's not used?

2020-11-12 22:49 UTC, pawels-optimizely approved these changes

2020-11-13 00:22 UTC, merged