fix:Change Log level from WARN to DEBUG for number values in Audience Conditions for revisionNumber
optimizely/java-sdk pull request #459
Opened 2022-01-20 16:33 UTC by The-inside-man

## Summary
- Changing log level from WARN to DEBUG for Audience Conditions when UnknownMatchTypeException or UnexpectedValueTypeException are caught.

Several customers have expressed concerns with logs being blown up with warnings due to usage of numbers for revisionNumber and other instances that require the use of a number value in their application where the SDK expects a string value. To avoid warnings in production environments, the log-level has been changed to DEBUG only now for those instances.

## Test plan
- New Unit Test
- FSC

## Issues
- "OASIS-8129"

2022-01-24 13:29 UTC, The-inside-man commented
@jaeopt Could you please take a look at this. All I have done is change the Log level for when the exception is caught to avoid blowing up the logs for the unknown and incorrect types.

2022-01-24 13:34 UTC, dustin-sier approved these changes
LGTM. I checked C# (its debug) and looking through Go to see if we're doing similar.

2022-01-24 17:32 UTC, jaeopt requested changes
I think we should stick to WARN level for UnknownMatchTypeException and UnexpectedValueTypeException. It must be an error on their settings.
The one with potentially exploding log messages is when they do not provide attribute for audience (instead of wrong type). It's interesting that the code already logs missing attribute as a debug level with correct messages (line 97).

2022-02-11 18:23 UTC, closed without merging

2022-02-11 18:25 UTC, jaeopt commented
We'll keep the current WARNING level for these issues. It's confirmed that we currently generate a DEBUG level log for missing attribute as expected. The only  issue was with Sematic Version, which has been fixed with https://github.com/optimizely/java-sdk/pull/463.